// Copyright © 2020-present Derek Thurn

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//    https://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

namespace Nighthollow.Model
{
  /// <summary>
  /// Represents a template for generating a random affix. The values in "Low" correspond to the lowest-possible numeric
  /// stat values to generate for this affix, while the values in "high" represent the highest-possible numeric values.
  /// Typically, an Affix is generated by selecting a value within this range uniformly at random.
  /// </summary>
  public sealed class AffixTemplateData
  {
    public AffixData Low { get; }
    public AffixData High { get; }

    public AffixTemplateData(AffixData low, AffixData high)
    {
      Low = low;
      High = high;
    }

    public AffixTemplateData Clone() => new AffixTemplateData(Low.Clone(), High.Clone());
  }
}