// Copyright © 2020-present Derek Thurn

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//    https://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#nullable enable

namespace Nighthollow.Model
{
  /// <summary>
  /// Represents a template for generating a random card. The values in "Low" correspond to the lowest-possible numeric
  /// stat values to generate for this card, while the values in "high" represent the highest-possible numeric values.
  /// Typically, a Card Item is generated by selecting a value within this range uniformly at random.
  /// </summary>
  public sealed class CardTemplateData
  {
    public CardItemData Low { get; }
    public CardItemData High { get; }

    public CardTemplateData(CardItemData low, CardItemData high)
    {
      Low = low;
      High = high;
    }

    public CardTemplateData Clone() => new CardTemplateData(Low.Clone(), High.Clone());
  }
}